services:
  posty:
    image: localhost:5000/posty:latest
    env_file: .env
    environment:
      DATA_DIR: /data
    volumes:
      - data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == null
      restart_policy:
        condition: on-failure
        delay: 30s

volumes:
  data:
